### ISSUE TITLE
MCA ChunkSection biomes processed incorrectly

### ISSUE THREAD

**Issue by SuperKael** [jglrxavpok/Hephaistos#23]
On line 150 of org.jglrxavpok.hephaistos.mca.ChunkSection, `sizeInBits` is defined as `compressedBiomes.size * 64 / biomeArraySize`. This is incorrect, and causes the wrong biomes to be read from the file, and even causes an exception to be thrown on line 158 if the ChunkSection contains 5 or more biomes. `sizeInBits` should be `ceil(log2(biomePalette.elements.size))`. I would make a PR to fix this, but I am not familiar with Kotlin, and I would not know how to properly test the fix.

**Comment by SuperKael** [comment]
Additionally, if the entire chunk only has one biome, `baseBiome` is assigned as `biomePalette.elements[0]` on line 145. However, `baseBiome` is only used if `biomes` is null - but it never is, since `biomes` was already initialized on line 139. As such, all chunks with only one biome will be `Biome.UnknownBiome` rather than the biome that they are meant to be.

**Comment by SuperKael** [comment]
Although I do not know how to properly build this (and Minestom itself, for that matter...), I just confirmed using Recaf (A Java de/recompilation tool) that my fix works.
Before (For visualization purposes, I have made Biome.UnknownBiome's water color red. Note not only the bad biomes, but also the handful of missing chunks in the top-right area of the image):
![image](https://user-images.githubusercontent.com/10406707/174444290-5525062b-d3d4-4a94-ae59-89d70431d446.png)

After:
![image](https://user-images.githubusercontent.com/10406707/174444299-4728a93f-5945-4b21-a0ad-185a729a8ecc.png)

**Comment by jglrxavpok** [comment]
Nice find, thank you!
