### ISSUE TITLE
AnvilException in ChunkColumn#getEntities()

### ISSUE THREAD

**Issue by DustKing5** [jglrxavpok/Hephaistos#24]
Hi!
I want to load entities from my world (in minestom, version 1.19) and when I try to list the entities in ChunkColumn I get an AvilException named "Missing field named 'xPos' (or of wrong type)".
My code:
```
            Path path = Path.of("world/entities");

            int regionX = CoordinatesKt.chunkToRegion(event.getChunkX());
            int regionZ = CoordinatesKt.chunkToRegion(event.getChunkZ());

            Path regionPath = Path.of(RegionFile.Companion.createFileName(regionX, regionZ));

            try {
                RegionFile regionFile = new RegionFile(new RandomAccessFile(path.resolve(regionPath).toFile(), "rw"), regionX, regionZ, event.getInstance().getDimensionType().getMaxY() - 1);
                ChunkColumn chunkColumn = regionFile.getChunk(event.getChunkX(), event.getChunkZ());
                if (chunkColumn == null) {
                    return;
                }
                List<NBTCompound> list = chunkColumn.getEntities().asListView();
                System.out.println(list);
            } catch (AnvilException | IOException e) {
                throw new RuntimeException(e);
            }
```
I attach the compressed world file.
[world.zip](https://github.com/jglrxavpok/Hephaistos/files/9046219/world.zip)

**Comment by jglrxavpok** [comment]
Hello,

Loading entities from the entities folder will not work if you use
ChunkColumn, you will need to use RegionFile#getChunkData and parse the nbt
yourself.
I plan on improvising this a bit in a future update but for now you don't
have a choice.

The technical reason is that the nbt does not have the same format at all
for entity chunk or "regular" chunks (ie block, block entities, binômes,
etc.)

**Comment by hteppl** [comment]
@jglrxavpok how i can parse NBT from RegionFile#getChunkData getList("Entities")?
