### ISSUE TITLE
Big floating point variables cannot be parsed

### ISSUE THREAD

**Issue by Argedon** [jglrxavpok/Hephaistos#29]
Deserializing following NBT's results in scientific notation number, which throws exception when trying to parse it.

```kotlin
val double = NBTDouble(10000000.0)
val float = NBTFloat(10000000F)
// Double -> 1.0E7D
// Float -> 1.0E7F

val doubleSNBT = double.toSNBT()
val floatSNBT = float.toSNBT()

try {
    SNBTParser(StringReader(doubleSNBT)).parse()
} catch (ex: NBTException) { ex.printStackTrace() }

try {
     SNBTParser(StringReader(floatSNBT)).parse()
} catch (ex: NBTException) { ex.printStackTrace() }
```

Throws:
> Double: Failed to parse SNBT: Line 1, column 3 extraneous input 'E7D' expecting (EOF) ( {',', '}'} when parsing NBTCompound )
> Float: Failed to parse SNBT: Line 1, column 3 extraneous input 'E7F' expecting (EOF)

**Comment by jglrxavpok** [comment]
Will be fixed in next release
