### ISSUE TITLE
Write & Read for netty buffers

### ISSUE THREAD

**Issue by hinoobers** [jglrxavpok/Hephaistos#31]
is there a tutorial for writing nbt to netty buffers and reading them from it?

**Comment by jglrxavpok** [comment]
Sorry for the (very) late answer:

Use `NBTWriter` pointing to an `OutputStream` capable of writing to a Netty buffer, or alternatively, use `NBTWriter` with a `ByteArrayOutputStream` and write the resulting byte array to your buffer directly.
