### ISSUE TITLE
Bug: ChunkReader.getYRange() includes empty chunk sections

### ISSUE THREAD

**Issue by NotThatRqd** [jglrxavpok/Hephaistos#35]
You can see Eoghanmc22 and I as we were figuring this out [here](https://discord.com/channels/706185253441634317/706186227493109860/1142949552580739082) in the [Minestom discord server](https://discord.gg/rV24CzG)

When placing a block that emits light at the height limit* (y=319) a server like Paper will save a chunk section with the lighting information. getYRange() should not include chunk sections that can not have blocks and do not have any block data, or there should be a separate function for Y range only including chunk sections with block data.

![image](https://github.com/jglrxavpok/Hephaistos/assets/67846317/a6ec27ed-9099-4019-a163-74a760471391)

The chunk with a Y of 20 should be ignored because it is past the build height and has no block data 

*This also probably happens when placing a block that emits light at the height min, but I haven't tested it

**Comment by jglrxavpok** [comment]
I have merged your fix, thanks!
