### ISSUE TITLE
Incorrect String Escaping in SNBTParser

### ISSUE THREAD

**Issue by Moulberry** [jglrxavpok/Hephaistos#8]
Deserializing the following String results in incorrectly escaped output.

```java
String input = "{\"Unbreakable\":1B,\"CustomModelData\":22,\"item_id\":\"test_back\",\"display\":{\"Lore\":[\"{\\\"text\\\":\\\"This is a test backpack! Used for wearing and testing! Put it on your back slot!\\\"}\"],\"Name\":\"{\\\"text\\\":\\\"Test Backpack\\\"}\"}}";
NBTCompound compound;
try {
        compound = (NBTCompound) new SNBTParser(new StringReader(input)).parse();
} catch (final NBTException e) {
        throw new RuntimeException(e);
}
```

Output:
`{"Unbreakable":1B,"CustomModelData":22,"item_id":"test_back","display":{"Lore":["{\\"text\\":\\"This is a test backpack! Used for wearing and testing! Put it on your back slot!\\"}"],"Name":"{\\"text\\":\\"Test Backpack\\"}"}}`

Expected Output:
`{"Unbreakable":1B,"CustomModelData":22,"item_id":"test_back","display":{"Lore":["{\"text\":\"This is a test backpack! Used for wearing and testing! Put it on your back slot!\"}"],"Name":"{\"text\":\"Test Backpack\"}"}}`

It should be possible to run `compound.toString()` back through an SNBTParser. Trying to do so with this incorrect escaping, like so:
```java
String result = compound.toString(); //This should be the same as input
try {
        compound = (NBTCompound) new SNBTParser(new StringReader(result)).parse();
} catch (final NBTException e) {
        throw new RuntimeException(e);
}
```

Throws an error:
> Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 2 path $.

**Comment by jglrxavpok** [comment]
Fixed.
